name = "chosung-game"
compatibility_date = "2024-11-19"

[[durable_objects.bindings]]
name = "GAME_STATE"
class_name = "GameStateRoom"

[[migrations]]
tag = "v1-game-state"
new_classes = ["GameStateRoom"]

